[tool.poetry]
name = "sparrow-cu-trail"
version = "0.1.0"
description = ""
authors = ["Daven Quinn <code@davenquinn.com>"]
readme = "README.md"
packages = [{ include = "plugins" }]

[tool.poetry.dependencies]
python = "^3.11"
pytest = "^8.3.2"
hecalc = "^1.0.0"
sparrow = { path = "../../Software/Sparrow/backend", develop = true }


[tool.poetry.group.dev.dependencies]
black = "^24.8.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
